feature:  * dc-run/dc-start upgrade: use DEVOPS_COMPOSE_PATH to set the search path list of compose yml file;
upgrade:
 * Add chromium into base image;
 * Upgrade nodejs to 14.17.1 in nodejs image.

diff --git a/develop-tools/@tools/shell-scripts/lib/prepare b/develop-tools/@tools/shell-scripts/lib/prepare
--- a/develop-tools/@tools/shell-scripts/lib/prepare
+++ b/develop-tools/@tools/shell-scripts/lib/prepare
@@ -8,7 +8,7 @@
 #                   directory for container's runtime data is recommended);
 #   - WORKING_DIR: Full filename of the current working directory
 #                  (For an interactive shell container, It's always mapped to /workspace);
-#   - POSITION_ID: A string which identify current working directory ($WORKING_DIR, replace "/" with "^")
+#   - POSITION_ID: A string which identify current working directory ($WORKING_DIR, replace "/" with ".")
 #                  (To separate the data file's position from containers which has a same image but started
 #                   from different working directory)
 #   - RUNTIME_DIR = ${DOCKER_BASE}/${COMPOSE_NAME}/${POSITION_ID}
@@ -50,33 +50,53 @@ bldblu=${txtbld}$(tput setaf 4) #  blue
 bldwht=${txtbld}$(tput setaf 7) #  white
 txtrst=$(tput sgr0)             # Reset
 
-export DOCKER_BASE="$HOME/.platbase-devops-docker/@${COMPOSE_TYPE}"
-if [ ! -z $DEVOPS_DOCKER_DATA_BASE ]; then
-    export DOCKER_BASE="$DEVOPS_DOCKER_DATA_BASE/@${COMPOSE_TYPE}"
-fi
-echo "${bldblu}NOTE:${txtrst} Read docker-compose definition(*.yml) from ${bldgrn}$DOCKER_BASE${txtrst}" >&2
-
 if  [ -z $1 ]; then
     echo "${bldred}ERROR:${txtrst} Argument missed - the compose name(docker-compose yml file's name without 'yml' extension" >&2
     echo "(For example, command '$0 nodejs' will start file '$DOCKER_BASE/nodejs.yml')" >&2
     exit -1
 fi
-
 export COMPOSE_NAME="$1"
-YML_FILE="$DOCKER_BASE/$COMPOSE_NAME.yml"
 
+# Find compose file by COMPOSE_TYPE in DEVOPS_COMPOSE_PATH
+if [ -z $DEVOPS_COMPOSE_PATH ]; then
+	# Default value - current path, then user home
+    export DEVOPS_COMPOSE_PATH="./@${COMPOSE_TYPE}:$HOME/.platbase-devops-docker/@${COMPOSE_TYPE}"
+    #Compatible with DEVOPS_DOCKER_DATA_BASE environment variable
+	if [ ! -z $DEVOPS_DOCKER_DATA_BASE ]; then
+	    export DEVOPS_COMPOSE_PATH="$DEVOPS_COMPOSE_PATH:$DEVOPS_DOCKER_DATA_BASE/@${COMPOSE_TYPE}"
+	fi
+fi
+echo "${bldblu}NOTE:${txtrst} Read docker-compose definition(*.yml) from ${bldgrn}$DEVOPS_COMPOSE_PATH${txtrst}" >&2
+
+_FOUND="NO";
+for _PATH in $(tr ':' '\n' <<< "$DEVOPS_COMPOSE_PATH"); do
+	_TMP="$_PATH/$COMPOSE_NAME.yml"
+	if [ -f "$_TMP" ]; then
+		_FOUND="YES"
+		export DOCKER_BASE="$(cd "$_PATH"; pwd)"
+		export YML_FILE="$(cd "$_PATH"; pwd)/$COMPOSE_NAME.yml"
+		echo "${bldblu}NOTE:${txtrst} Docker-compose definition(*.yml) found in ${bldgrn}$YML_FILE${txtrst}" >&2
+		break
+	fi
+done
+if [ "$_FOUND" == "NO" ]; then
+    echo "${bldred}ERROR:${txtrst} Can't find docker-compose file ${bldred}$COMPOSE_NAME.yml${txtrst} in ${bldgrn}$DEVOPS_COMPOSE_PATH${txtrst}" >&2
+    exit -1	
+fi
 if [ ! -f "$YML_FILE" ]; then
-    echo "${bldred}ERROR:${txtrst} docker-compose file ${bldwht}$YML_FILE${txtrst} missing" >&2
+    echo "${bldred}ERROR:${txtrst} Docker-compose file ${bldwht}$YML_FILE${txtrst} missing" >&2
     exit -1
 fi
 
 export WORKING_DIR="`pwd`"
 
-# "Position ID" for WORKING_DIR(replace "/" to "^")
+# "Position ID" for WORKING_DIR(replace "/" to ".")
 POSITION_ID="${WORKING_DIR}"
-export POSITION_ID="${POSITION_ID//\//^}"
+export POSITION_ID="${POSITION_ID//$HOME\//.}"
+export POSITION_ID="${POSITION_ID//\//.}"
 
 export RUNTIME_DIR=${DOCKER_BASE}/${COMPOSE_NAME}/${POSITION_ID}
+mkdir -p "$RUNTIME_DIR"
 echo "${bldblu}NOTE:${txtrst} (recommended) to store container's runtime data in ${bldgrn}$RUNTIME_DIR${txtrst}" >&2
 
 # Three ports between 8080-9080，18080-19080, 28080-29080
